version: "3.3"

services:
  mongo:
    image: mongo:latest
    ports: 27017:27017
    environment:
      MONGO_INITDB_DATABASE: laupqq
  
  webapp:
    build:
      context: ..
      dockerfile.: ./Dockerfile
    ports: 80:3000